antelopes: 'snort'
badgers: 'growl'
bats: 'screech'
bees: 'buzz'
tigers: 'roar'
bitterns: 'boom'
cats: 'meow'
chickens: 'cluck'
chinchillas: 'squeak'
cicadas: 'chirp'
cattle: 'moo'
crickets: 'chirp'
crows: 'caw'
curlews: 'pipe'
deer: 'bellow'
dogs: 'woof'
dolphins: 'click'
donkeys: 'hee-haw'
ducks: 'qua'
eagles: 'scream'
elephants: 'trump'
elk: 'bugle (male),'
ferrets: 'dook'
frogs: 'croak'
giraffes: 'bleat'
geese: 'ho'
grasshoppers: 'chirp'
guinea pigs: 'squeak'
hamsters: 'squeak'
hares: 'squeak'
hermit crabs: 'chirp'
horses: 'neigh'
hippopotamuses: 'growl'
linnets: 'chuckle'
magpies: 'chatter'
mice: 'sque'
moose: 'bellow'
mosquitos: 'whine'
okapis: 'bellow'
oxen: 'low'
owls: 'ho'
peacocks: 'scream'
pigs: 'oink'
pigeons: 'coo'
prairie dogs: 'bark'
raccoons: 'trill'
ravens: 'nevermore'
rhinoceros: 'bellow'
rooks: 'caw'
seals: 'bark'
sheep: 'baa'
snakes: 'hiss'
songbirds: 'chirp'
swans: 'cry'
tapirs: 'squeak'
tokay geckos: 'croak'
turkeys: 'gobble'
vultures: 'scream'
walruses: 'groan'
whales: 'sing'
fox: '?????'
